from flask import Flask,render_template,make_response,redirect,url_for
import datetime

app=Flask("__main__")

@app.route('/home',methods=['post','get'])
def home():
    now=datetime.datetime.now()
    return render_template('home.html',curr_now=now)

@app.route('/about')
def about():
    headers={
        'content-Type':'application/json'
    }
    return make_response('This response is generated by make response',200,headers
                         )

# @app.route('/base')
# def base():
#     # return redirect('/home')
#     return redirect(url_for('home'))




@app.route('/base')
def base2():
    return render_template('base.html')



@app.route('/ap1')
def greet():
    curr1=datetime.time.now()
    return render_template('home.html',curr1)






if __name__=='__main__':
    app.run(debug=True)